name: App CD

on:
  pull_request:
    types: [labeled]
    paths-ignore:
      - README.md

jobs:
  app-cd:
    name: 'App CD'
    uses: ./.github/workflows/node-publish.yml
    secrets: inherit
    with:
      APP_NAME: cronjs
