name: Node Publish

on:
  workflow_call:
    inputs:
      APP_NAME:
        required: true
        type: string
      APP_DIR:
        required: false
        type: string
        default: '.'

jobs:
  app-ci:
    name: 'App CI'
    if: github.event.label.name == 'publish npm' && github.event.pull_request.mergeable && github.event.pull_request.draft == false
    uses: ./.github/workflows/node-ci.yml
    secrets: inherit
    with:
      APP_NAME: ${{ inputs.APP_NAME }}
      SKIP_REMOVE_LABELS: true

  publish-npm:
    name: 'Publish Npm'
    runs-on: ubuntu-latest
    needs: [app-ci]
    env:
      ENV_NAME: prd
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: ./.github/actions/setup-node
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run Build
        run: npm run 'ci:build'
      - name: Publish to NPM
        run: npm run 'ci:publish'
      - name: Merge PR
        uses: pascalgn/automerge-action@v0.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: 'publish npm'
          MERGE_METHOD: squash
